+incdir+${APLC_TB_HOME}/tb/if
+incdir+${APLC_TB_HOME}/tb/env
+incdir+${APLC_TB_HOME}/tb/uvc/spi_agent
+incdir+${APLC_TB_HOME}/tc
+incdir+${APLC_TB_HOME}/seq
+incdir+${VIP_SPI_HOME}
+incdir+${APLC_RTL_HOME}

${APLC_RTL_HOME}/APLC_LITE.sv
${APLC_RTL_HOME}/SLC_TASKALLO.sv
${APLC_RTL_HOME}/SLC_BANK.sv
${APLC_RTL_HOME}/SLC_CAXIS.sv
${APLC_RTL_HOME}/SLC_DPCHK.sv
${APLC_RTL_HOME}/SLC_CCMD.sv
${APLC_RTL_HOME}/SLC_SAXIS.sv
${APLC_RTL_HOME}/SLC_SCTRL_FRONT.sv
${APLC_RTL_HOME}/SLC_TPIPE.sv
${APLC_RTL_HOME}/SLC_DPIPE.sv
${APLC_RTL_HOME}/SLC_SAXIM.sv
${APLC_RTL_HOME}/SLC_RXFIFO.sv
${APLC_RTL_HOME}/SLC_TXFIFO.sv
${APLC_RTL_HOME}/SLC_WBB.sv
${APLC_RTL_HOME}/SLC_SCTRL_BACK.sv
${APLC_RTL_HOME}/SLC_CSRFILE.sv

${VIP_SPI_HOME}/aplc_spi_if.sv
${VIP_SPI_HOME}/aplc_spi_pkg.sv

${APLC_TB_HOME}/tb/if/aplc_csr_if.sv
${APLC_TB_HOME}/tb/env/aplc_tb_pkg.sv
${APLC_TB_HOME}/tb/tb_top.sv
