$CRG_UVC_PATH/crg_pkg.sv
$DV_ROOT/hw/APLC_LITE/tb/if/csr_if.sv
$DV_ROOT/hw/APLC_LITE/tb/if/fifo_if.sv
$DV_ROOT/hw/APLC_LITE/tb/if/if_harness.sv
$DV_ROOT/hw/APLC_LITE/tb/if/spi_if.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/csr_agent/csr_defines.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/csr_agent/csr_transaction.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/csr_agent/csr_agent_cfg.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/csr_agent/csr_monitor.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/csr_agent/csr_agent.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/fifo_agent/fifo_defines.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/fifo_agent/fifo_transaction.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/fifo_agent/fifo_agent_cfg.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/fifo_agent/fifo_monitor.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/fifo_agent/fifo_agent.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/spi_agent/spi_defines.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/spi_agent/spi_transaction.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/spi_agent/spi_agent_cfg.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/spi_agent/spi_driver.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/spi_agent/spi_monitor.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/spi_agent/spi_sequencer.sv
$DV_ROOT/hw/APLC_LITE/tb/uvc/spi_agent/spi_agent.sv
$DV_ROOT/hw/APLC_LITE/tb/env/APLC_LITE_rm.sv
$DV_ROOT/hw/APLC_LITE/tb/env/APLC_LITE_scoreboard.sv
$DV_ROOT/hw/APLC_LITE/tb/env/APLC_LITE_env_defines.sv
$DV_ROOT/hw/APLC_LITE/tb/env/APLC_LITE_env.sv
$DV_ROOT/hw/APLC_LITE/tb/tb_top.sv
